services:
  minecraft-server-fabric:
    image: itzg/minecraft-server
    container_name: minecraft-server-fabric
    restart: unless-stopped
    environment:
      MEMORY: 16G
      USE_AIKAR_FLAGS: TRUE
      ENABLE_ROLLING_LOGS: TRUE
      TZ: Etc/UTC
      EULA: "TRUE"
      MOD_PLATFORM: MODRINTH
      MODRINTH_MODPACK: $MODPACK
      MODRINTH_VERSION: $FABRIC_MODRINTH_VERSION
      LEVEL_TYPE: $FABRIC_LEVEL_TYPE
      MOTD: $FABRIC_MOTD
      OPS: $OPS
      SNOOPER_ENABLED: FALSE
    volumes:
      - "/opt/minecraft/minecraft-server-fabric:/data"

  minecraft-server-neoforge:
    image: itzg/minecraft-server
    container_name: minecraft-server-neoforge
    restart: unless-stopped
    environment:
      MEMORY: 16G
      USE_AIKAR_FLAGS: TRUE
      ENABLE_ROLLING_LOGS: TRUE
      TZ: Etc/UTC
      EULA: "TRUE"
      MOD_PLATFORM: MODRINTH
      MODRINTH_MODPACK: $MODPACK
      MODRINTH_VERSION: $NEOFORGE_MODRINTH_VERSION
      LEVEL_TYPE: $NEOFORGE_LEVEL_TYPE
      MOTD: $NEOFORGE_MOTD
      OPS: $OPS
      SNOOPER_ENABLED: FALSE
    volumes:
      - "/opt/minecraft/minecraft-server-neoforge:/data"

  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      TZ: Etc/UTC
      TUNNEL_TOKEN: $TOKEN

  router:
    image: itzg/mc-router
    container_name: mc-router
    restart: unless-stopped
    depends_on:
      - minecraft-server-fabric
      - minecraft-server-neoforge
      - cloudflared
    environment:
      MAPPING: |
        $FABRIC_SERVER=fabric:25565
        $NEOFORGE_SERVER=neoforge:25565
    ports:
      - "25565:25565"
