services:
  minecraft-server-fabric:
    image: itzg/minecraft-server
    container_name: minecraft-server-fabric
    restart: unless-stopped
    environment:
      TZ: Etc/UTC
      MEMORY: 16G
      USE_AIKAR_FLAGS: TRUE
      ENABLE_ROLLING_LOGS: TRUE
      EULA: TRUE
      SNOOPER_ENABLED: FALSE
      MOD_PLATFORM: MODRINTH
      MODRINTH_MODPACK: $MODPACK
      MODRINTH_VERSION: $FABRIC_MODRINTH_VERSION
      LEVEL_TYPE: $LEVEL_TYPE
      MOTD: $FABRIC_MOTD
      OPS: $OPS
    volumes:
      - "/opt/minecraft/minecraft-server-fabric:/data"

  minecraft-server-neoforge:
    image: itzg/minecraft-server
    container_name: minecraft-server-neoforge
    restart: unless-stopped
    environment:
      TZ: Etc/UTC
      MEMORY: 16G
      USE_AIKAR_FLAGS: TRUE
      ENABLE_ROLLING_LOGS: TRUE
      EULA: TRUE
      SNOOPER_ENABLED: FALSE
      MOD_PLATFORM: MODRINTH
      MODRINTH_MODPACK: $MODPACK
      MODRINTH_VERSION: $NEOFORGE_MODRINTH_VERSION
      LEVEL_TYPE: $LEVEL_TYPE
      MOTD: $NEOFORGE_MOTD
      OPS: $OPS
    volumes:
      - "/opt/minecraft/minecraft-server-neoforge:/data"

  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      TZ: Etc/UTC
      TUNNEL_TOKEN: $TOKEN
